domain: example.com
url: https://randallspqr.github.io/birdsinmybedroom.github.io/
baseurl: "/birdsinmybedroom.github.io/"

title: ğŸ¦ ğŸ›Œ
email: wind@example.com
author: Jess Coghan

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  tiktok: "https://www.tiktok.com/@jessicakia"
  instagram: "https://www.instagram.com/birdsinmybedroom"
  twitter: "https://x.com/jessicakia"
  bluesky: "https://bsky.app/profile/jessicakia"
  facebook: "https://www.facebook.com/jessicacogan"
  threads: "https://www.threads.net/@jessicakia"
  youtube: "https://www.youtube.com/@birdsinmybedroom"